School.Web/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models
{
    public class Student
    {
        public Student()
        {
            CreatedAt = DateTime.Now;
        }

        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public DateTime BirthDate { get; set; }
        
        public int ClassId { get; set; }
        public virtual Class Class { get; set; }

        public DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }

        public virtual List<LessonDetail> LessonDetails { get; set; }
    }
}

School.Web/Models/ViewModels/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models.ViewModels
{
    public class StudentViewModel
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public DateTime? BirthDate { get; set; }

        public int ClassId { get; set; }
        public string ClassName { get; set; }
    }
}

School.Web/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Web.Models;
using AutoMapper;
using School.Web.Models.ViewModels;

namespace School.Web.Controllers
{
    public class ClassController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Class
        public async Task<ActionResult> Index()
        {
            var classs = await db.Classes.Where(x => x.IsDeleted == false).ToListAsync();
            var viewModels = Mapper.Map<List<ClassViewModel>>(classs);

            return View(viewModels);
        }

        // GET: Class/Create
        public ActionResult Create()
        {
            var viewModel = new ClassViewModel();

            return View(viewModel);
        }

        // POST: Class/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClassViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var cls = Mapper.Map<Class>(viewModel);

                db.Classes.Add(cls);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Class/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cls = await db.Classes.FindAsync(id);
            if (cls == null)
            {
                return HttpNotFound();
            }

            var viewModel = Mapper.Map<ClassViewModel>(cls);

            return View(viewModel);
        }

        // POST: Class/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ClassViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var cls = await db.Classes.FindAsync(viewModel.ClassId);

                Mapper.Map(viewModel, cls);

                db.Entry(cls).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Class/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cls = await db.Classes.FindAsync(id);
            if (cls == null)
            {
                return HttpNotFound();
            }

            cls.IsDeleted = true;

            db.Entry(cls).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School.Web/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Web.Models;
using AutoMapper;
using School.Web.Models.ViewModels;

namespace School.Web.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Student
        public async Task<ActionResult> Index()
        {
            var students = await db.Students.Where(x => x.IsDeleted == false).ToListAsync();
            var viewModels = Mapper.Map<List<StudentViewModel>>(students);

            return View(viewModels);
        }

        // GET: Student/Create
        public async Task<ActionResult> Create()
        {
            var viewModel = new StudentViewModel();

            await CreateSelectLists();

            return View(viewModel);
        }

        // POST: Student/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StudentViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var student = Mapper.Map<Student>(viewModel);

                db.Students.Add(student);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Student/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var student = await db.Students.FindAsync(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            var viewModel = Mapper.Map<StudentViewModel>(student);

            var cls = await db.Classes.Where(x => x.IsDeleted == false)
               .Select(x => new { x.ClassId, ClassName = x.Number + x.Prefix })
               .ToListAsync();
            ViewBag.Classes = new SelectList(cls, "ClassId", "ClassName");

            return View(viewModel);
        }

        // POST: Student/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(StudentViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var student = await db.Students.FindAsync(viewModel.StudentId);

                Mapper.Map(viewModel, student);

                db.Entry(student).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Student/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var student = await db.Students.FindAsync(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            student.IsDeleted = true;

            db.Entry(student).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var student = await db.Students.FindAsync(id);
            db.Students.Remove(student);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private async Task CreateSelectLists()
        {
            var cls = await db.Classes.Where(x => x.IsDeleted == false)
                .Select(x => new { x.ClassId, ClassName = x.Number + x.Prefix })
                .ToListAsync();
            ViewBag.Classes = new SelectList(cls, "ClassId", "ClassName");
        }
    }
}

School.Web/Views/Student/Create.cshtml
@model School.Web.Models.ViewModels.StudentViewModel
@{
    ViewBag.Title = "Добавить ученика";
}

<div class="row">
    <div class="span3">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Student")">
                    <i class="menu-icon icon-circle-arrow-left"></i>Назад
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="module">
    <div class="module-head">
        <h3>Добавление ученика</h3>
    </div>
    <div class="module-body">
        <form class="form-horizontal row-fluid" action="@Url.Action("Create")" method="post">
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.StudentId)

            <div class="control-group">
                <label class="control-label" for="basicinput">Фамилия</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "span8", @placeholder = "Введите фамилию..." })
                    @Html.ValidationMessageFor(m => m.LastName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Имя</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "span8", @placeholder = "Введите имя..." })
                    @Html.ValidationMessageFor(m => m.FirstName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Отчество</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.MiddleName, new { @class = "span8", @placeholder = "Введите отчество..." })
                    @Html.ValidationMessageFor(m => m.MiddleName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Дата рождения</label>
                <div class="controls" style="position: relative;">
                    @Html.TextBoxFor(m => m.BirthDate, new { @class = "span4 datepicker", @placeholder = "Введите дату..." })
                    @Html.ValidationMessageFor(m => m.BirthDate)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Класс</label>
                <div class="controls">
                    @Html.DropDownListFor(m => m.ClassId, (SelectList) ViewBag.Classes, "", new { @class = "span8", @data_placeholder = "Выберите класс..." })
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('.datepicker').datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY',
                useCurrent: true
            });
        });
    </script>
}

School.Web/Views/Student/Edit.cshtml
@model School.Web.Models.ViewModels.StudentViewModel
@{
    ViewBag.Title = "Редактировать ученика";
}

<div class="row">
    <div class="span3">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Student")">
                    <i class="menu-icon icon-circle-arrow-left"></i>Назад
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="module">
    <div class="module-head">
        <h3>Редактирвоание ученика</h3>
    </div>
    <div class="module-body">
        <form class="form-horizontal row-fluid" action="@Url.Action("Edit")" method="post">
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.StudentId)

            <div class="control-group">
                <label class="control-label" for="basicinput">Фамилия</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "span8", @placeholder = "Введите фамилию..." })
                    @Html.ValidationMessageFor(m => m.LastName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Имя</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "span8", @placeholder = "Введите имя..." })
                    @Html.ValidationMessageFor(m => m.FirstName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Отчество</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.MiddleName, new { @class = "span8", @placeholder = "Введите отчество..." })
                    @Html.ValidationMessageFor(m => m.MiddleName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Дата рождения</label>
                <div class="controls" style="position: relative;">
                    @Html.TextBoxFor(m => m.BirthDate, new { @class = "span4 datepicker", @placeholder = "Введите дату..." })
                    @Html.ValidationMessageFor(m => m.BirthDate)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Класс</label>
                <div class="controls">
                    @Html.DropDownListFor(m => m.ClassId, (SelectList)ViewBag.Classes, "", new { @class = "span8", @data_placeholder = "Выберите класс..." })
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('.datepicker').datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY',
                useCurrent: true
            });
        });
    </script>
}

School.Web/Views/Student/Index.cshtml
@model IEnumerable<School.Web.Models.ViewModels.StudentViewModel>
@{
    ViewBag.Title = "Ученики";
}

<div class="span3">
    <div class="sidebar">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Home")">
                    <i class="menu-icon icon-circle-arrow-left"></i>К разделам
                </a>
            </li>
        </ul>

        <ul class="widget widget-menu unstyled">
            <li class="active">
                <a href="@Url.Action("Index", "Student")">
                    <i class="menu-icon icon-user"></i>Ученики
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Class")"><i class="menu-icon icon-list"></i>Классы</a>
            </li>
        </ul>
        <!--/.widget-nav-->

        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Create", "Student")">
                    <i class="menu-icon icon-plus"></i>Добавить ученика
                </a>
            </li>
        </ul>
        <!--/.widget-nav-->
    </div>
    <!--/.sidebar-->
</div>
<!--/.span3-->
<div class="span9">
    <div class="content">
        <div class="module">
            <div class="module-head">
                <h3>
                    Ученики
                </h3>
            </div>
            <div class="module-body table">
                <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">
                    <thead>
                        <tr>
                            <th>
                                Фамилия
                            </th>
                            <th>
                                Имя
                            </th>
                            <th>
                                Отчество
                            </th>
                            <th>
                                Дата рождения
                            </th>
                            <th>
                                Класс
                            </th>
                            <th>
                                Действия
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var index = 0;
                            foreach (var student in Model)
                            {
                                <tr class="@(index % 2 == 0 ? "even" : "odd") gradeX">
                                    <td>
                                        @student.LastName
                                    </td>
                                    <td>
                                        @student.FirstName
                                    </td>
                                    <td>
                                        @student.MiddleName
                                    </td>
                                    <td class="center">
                                        @(student.BirthDate != null ? student.BirthDate.Value.ToShortDateString() : "")
                                    </td>
                                    <td class="center">
                                        @student.ClassName
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", new { id = student.StudentId })"><i class="icon-pencil" style="color: green;"></i></a>
                                        <a href="@Url.Action("Delete", new { id = student.StudentId })"><i class="icon-trash" style="color: red;"></i></a>
                                    </td>
                                </tr>
                            }
                        }
                 
                    </tbody>
                    @*<tfoot>
                            <tr>
                                <th>
                                    Rendering engine
                                </th>
                                <th>
                                    Browser
                                </th>
                                <th>
                                    Platform(s)
                                </th>
                                <th>
                                    Engine version
                                </th>
                                <th>
                                    CSS grade
                                </th>
                            </tr>
                        </tfoot>*@
                </table>
            </div>
        </div>
    </div>
    <!--/.content-->
</div>
<!--/.span9-->