School.Web/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models
{
    public class Lesson
    {
        public Lesson()
        {
            CreatedAt = DateTime.Now;
        }

        public int LessonId { get; set; }

        public DateTime LessonDate { get; set; }

        public int DisciplineId { get; set; }
        public virtual Discipline Discipline { get; set; }

        public string HomeWork { get; set; }

        public DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }

        public virtual List<LessonDetail> LessonDetails { get; set; }
    }
}

School.Web/Models/ViewModels/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models.ViewModels
{
    public class LessonViewModel
    {
        public int LessonId { get; set; }

        public DateTime LessonDate { get; set; }

        public int DisciplineId { get; set; }
        public DisciplineViewModel Discipline { get; set; }

        public string TeacherName { get; set; }

        public int NumberOfLessons { get; set; }
        public int AddedLessons { get; set; }

        public List<StudentViewModel> Students { get; set; }

        public string HomeWork { get; set; }

        public List<LessonDetailViewModel> LessonDetails { get; set; }
    }
}

School.Web/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Web.Models;
using AutoMapper;
using School.Web.Models.ViewModels;

namespace School.Web.Controllers
{
    public class LessonController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Lesson
        public async Task<ActionResult> Index()
        {
            var cls = await db.Classes.Where(x => x.IsDeleted == false)
                 .Select(x => new { x.ClassId, ClassName = x.Number + x.Prefix })
                 .ToListAsync();
            ViewBag.Classes = new SelectList(cls, "ClassId", "ClassName");

            var firstSeptember = new DateTime(DateTime.Today.Year - 1, 9, 1);
            //beware different cultures, see other answers
            var startOfFirstWeek = firstSeptember.AddDays(1 - (int)(firstSeptember.DayOfWeek));
            var weeks =
                Enumerable
                    .Range(0, 54)
                    .Select(i => new {
                        weekStart = startOfFirstWeek.AddDays(i * 7)
                    })
                    .TakeWhile(x => x.weekStart.Year <= firstSeptember.Year + 1)
                    .Select(x => new {
                        x.weekStart,
                        weekFinish = x.weekStart.AddDays(4)
                    })
                    .SkipWhile(x => x.weekFinish < firstSeptember.AddDays(1))
                    .Select((x, i) => new SelectListItem {
                        Text = x.weekStart.ToString("dd.MM.yyyy") + " - " + x.weekFinish.ToString("dd.MM.yyyy"),
                        // WeekNumber = i + 1,
                        Value = x.weekStart.ToShortDateString(),
                        Selected = DateTime.Now.StartOfWeek(DayOfWeek.Monday).ToString("dd.MM.yyyy") == x.weekStart.ToString("dd.MM.yyyy")
                    });

            ViewBag.Weeks = weeks; // new SelectList(weeks);

            return View();
        }

        // GET: Lesson
        public async Task<ActionResult> GetLessons(int? classId, int? disciplineId, string weekStart)
        {
            var startDate = DateTime.Parse(weekStart);
            var endDate = startDate.AddDays(8);
            var lessons = await db.Lessons.Where(x => x.DisciplineId == disciplineId && x.Discipline.ClassId == classId
                && x.LessonDate >= startDate && x.LessonDate <= endDate
                && x.IsDeleted == false).ToListAsync();
            var viewModels = Mapper.Map<List<LessonViewModel>>(lessons);

            var discipline = await db.Disciplines.SingleOrDefaultAsync(d => d.DisciplineId == disciplineId);

            ViewBag.NumberOfLessons = discipline.NumberOfLessons;
            ViewBag.TeacherName = discipline.Teacher.LastName + " " + (discipline.Teacher.FirstName != null ? discipline.Teacher.FirstName : "") + " "
                + (discipline.Teacher.MiddleName != null ? discipline.Teacher.MiddleName : "");
            ViewBag.AddedLessons = await db.Lessons.Where(x => x.DisciplineId == disciplineId 
                    && x.Discipline.ClassId == classId
                    && x.IsDeleted == false)
                .CountAsync();

            var students = await db.Students.Where(s => s.IsDeleted == false).ToListAsync();
            ViewBag.Students = Mapper.Map<List<StudentViewModel>>(students);

            return PartialView("_Lesson", viewModels);
        }

        public async Task<ActionResult> GetDisciplines(int? classId)
        {
            var disciplines = await db.Disciplines.Where(d => d.ClassId == classId && d.IsDeleted == false)
                .ToListAsync();

            var viewModels = Mapper.Map<List<DisciplineViewModel>>(disciplines);

            return Json(viewModels, JsonRequestBehavior.AllowGet);
        }

        // GET: Lesson/Create
        public ActionResult Create()
        {
            var viewModel = new LessonViewModel();

            return View(viewModel);
        }

        // POST: Lesson/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LessonViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var lesson = Mapper.Map<Lesson>(viewModel);

                db.Lessons.Add(lesson);
                await db.SaveChangesAsync();

                return Json("Success");
            }

            return null;
        }

        // POST: Lesson/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateDetail(LessonDetailViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var lessonDetail = Mapper.Map<LessonDetail>(viewModel);

                db.LessonDetail.Add(lessonDetail);
                await db.SaveChangesAsync();

                return Json("Success");
            }

            return null;
        }

        // GET: Lesson/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var lesson = await db.Lessons.FindAsync(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            var viewModel = Mapper.Map<LessonViewModel>(lesson);

            return View(viewModel);
        }

        // POST: Lesson/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LessonViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var lesson = await db.Lessons.FindAsync(viewModel.LessonId);

                Mapper.Map(viewModel, lesson);

                db.Entry(lesson).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Lesson/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var lesson = await db.Lessons.FindAsync(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            lesson.IsDeleted = true;

            db.Entry(lesson).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Lesson/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var lesson = await db.Lessons.FindAsync(id);
            db.Lessons.Remove(lesson);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    public static class DateTimeExtensions
    {
        public static DateTime StartOfWeek(this DateTime dt, DayOfWeek startOfWeek)
        {
            int diff = (7 + (dt.DayOfWeek - startOfWeek)) % 7;
            return dt.AddDays(-1 * diff).Date;
        }
    }

}

School.Web/Views/Lesson/Index.cshtml
@{
    ViewBag.Title = "Журнал";
}

<style>
    .table-hover-cells > tbody > tr > th:hover,
    .table-hover-cells > tbody > tr > td:hover {
        background-color: #f5f5f5;
    }

    .table-hover-cells > tbody > tr > th.active:hover,
    .table-hover-cells > tbody > tr > td.active:hover,
    .table-hover-cells > tbody > tr.active > th:hover,
    .table-hover-cells > tbody > tr.active > td:hover {
        background-color: #e8e8e8;
    }

    .table-hover.table-hover-cells > tbody > tr:hover > th:hover,
    .table-hover.table-hover-cells > tbody > tr:hover > td:hover {
        background-color: #e8e8e8;
    }

    .table-hover.table-hover-cells > tbody > tr.active:hover > th:hover,
    .table-hover.table-hover-cells > tbody > tr.active:hover > td:hover {
        background-color: #d8d8d8;
    }

    h1 > .divider:before,
    h2 > .divider:before,
    h3 > .divider:before,
    h4 > .divider:before,
    h5 > .divider:before,
    h6 > .divider:before,
    .h1 > .divider:before,
    .h2 > .divider:before,
    .h3 > .divider:before,
    .h4 > .divider:before,
    .h5 > .divider:before,
    .h6 > .divider:before {
        color: #777;
        content: "\0223E\0020";
    }
</style>

<div class="span12">
    <div class="content">
        <div class="module">
            <div class="module-head">
                <h3>
                    Журнал
                </h3>
            </div>
            <div class="module-option clearfix" style="border: none; padding-bottom: 0.5em;">
                <div class="pull-left">
                    Класс : &nbsp;
                    @*<div class="btn-group">
                        <button class="btn" style="width: 5em; text-align: left;">9а</button>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">9а</a></li>
                            <li><a href="#">9б</a></li>
                            <li><a href="#">10а</a></li>
                            <li><a href="#">10б</a></li>
                        </ul>
                    </div>*@
                    @Html.DropDownList("ClassId", (SelectList) ViewBag.Classes, "",  new { @id = "classes" })

                    &nbsp;&nbsp;&nbsp;&nbsp;
                    Дисциплина : &nbsp;
                    @*<div class="btn-group">
                        <button class="btn" style="text-align: left;">Алгебра</button>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Алгебра [Преподаватель: Афанасьева Г.В.]</a></li>
                            <li><a href="#">Информатика [Преподаватель: Бородин А.С.]</a></li>
                            <li><a href="#">Физика [Преподаватель: Орлов Д.С.]</a></li>
                        </ul>
                    </div>*@

                    <select id="disciplines"></select>

                    &nbsp;&nbsp;&nbsp;&nbsp;
                    Неделя : &nbsp;
                    @*<div class="btn-group">
                        <button class="btn">22.01.2018 - 28.01.2018</button>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">22.01.2018 - 28.01.2018</a></li>
                            <li><a href="#">29.01.2018 - 04.02.2018</a></li>
                            <li><a href="#">05.02.2018 - 11.02.2018</a></li>
                        </ul>
                    </div>*@
                    @Html.DropDownList("WeekStart", (IEnumerable<SelectListItem>) ViewBag.Weeks, new { @id = "weeks" })

                </div>
                <div class="pull-right">
                    <a href="#addLessonModal" data-toggle="modal"  class="btn btn-primary">Добавить занятие</a>
                </div>
            </div>

            <div id="journal"></div>

        </div>
    </div>
    <!--/.content-->
</div>
<!--/.span9-->


<div id="myModal" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Поставить оценку</h3>
    </div>

    <div class="modal-body">
        <form id="myModalForm" class="form-horizontal row-fluid" action="@Url.Action("CreateDetail", "Lesson")" method="post">
            <input type="hidden" name="LessonId" id="modalLessonId" />
            <input type="hidden" name="LessonDetailId" id="modalLessonDetailId" />
            <input type="hidden" name="StudentId" id="modalStudentId" />

            @Html.AntiForgeryToken()

            <div class="control-group">
                <label class="control-label">Оценка</label>
                <div class="controls">
                    <label class="radio">
                        <input type="radio" name="Grade" id="optionsRadios1" value="5" checked="">
                        5
                    </label>
                    <label class="radio">
                        <input type="radio" name="Grade" id="optionsRadios2" value="4">
                        4
                    </label>
                    <label class="radio">
                        <input type="radio" name="Grade" id="optionsRadios3" value="3">
                        3
                    </label>
                    <label class="radio">
                        <input type="radio" name="Grade" id="optionsRadios3" value="2">
                        2
                    </label>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    @*<label class="checkbox inline">
                        <input id="attention" type="checkbox" name="Attention">
                        Пометить как важное
                    </label>*@
                    @Html.CheckBox("Attention", new { id = "attention" })
                    Пометить как важное
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Коментарий</label>
                <div class="controls">
                    <textarea class="span8" rows="5" name="Comment"></textarea>
                </div>
            </div>
        </form>
    </div>

    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Отмена</a>
        <button id="myModalBtn" type="button" class="btn btn-primary">Сохранить</button>
    </div>
</div>

<div id="addLessonModal" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Добавить занятие</h3>
    </div>

    <div class="modal-body">
        <form id="addLessonForm" class="form-horizontal row-fluid" action="@Url.Action("Create", "Lesson")" method="post">
            <div class="control-group">
                @Html.AntiForgeryToken()

                <input type="hidden" id="modalDisciplineId" name="DisciplineId" />

                <label class="control-label" for="basicinput">Дата занятия</label>
                <div class="control-group">
                    <div class="controls" style="position: relative;">
                        @Html.TextBox("LessonDate", null, new { @class = "span6 datepicker", @placeholder = "Введите дату..." })
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Домашнее задание</label>
                <div class="controls">
                    <textarea class="span8" name="HomeWork" rows="5">Задания № 1, 9, 14 стр.105</textarea>
                </div>
            </div>
        </form>
    </div>

    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Отмена</a>
        <button type="button" class="btn btn-primary" id="addLessonModalBtn">Сохранить</button>
    </div>
</div>

@section Scripts {
<script>
        $(function () {
            $("#classes").change(function () {
                var classId = $(this).val();
                $.get('/Lesson/GetDisciplines?classId=' + classId, function (disciplines) {
                    var options = '<option></option>';

                    if (disciplines) {
                        $.each(disciplines, function (ind, discipline) {
                            options += "<option value='" + discipline.DisciplineId + "'>" + discipline.DisciplineName + "</option>";
                        });
                    }

                    $("#disciplines").html(options);
                });
            });

            $("#disciplines").change(function () {
                var disciplineId = $(this).val();
                $("#modalDisciplineId").val(disciplineId);
            });

            $("#classes, #disciplines, #weeks").change(function() {
                loadLessons();
            });

            $('.datepicker').datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY',
                useCurrent: true
            });

            $("#addLessonModalBtn").click(function () {
                var classId = $("#classes").val();
                var disciplineId = $("#disciplines").val();

                if (!classId) {
                    alert('Выберите класс!');
                    return;
                }

                if (!disciplineId) {
                    alert('Выберите дисциплину!');
                    return;
                }

                // $("#addLessonForm").submit();
                var formdata = new FormData($('#addLessonForm').get(0));
                $.ajax({
                    url: "@Url.Action("Create")",
                    type: 'POST',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    dataType: "json",
                    success: function (response) {
                        loadLessons();
                        $("#addLessonModal").modal('hide');
                    }
                });
            });

            $("#myModalBtn").click(function () {
                // $("#myModalForm").submit();

                var formdata = new FormData($('#myModalForm').get(0));
                $.ajax({
                    url: "@Url.Action("CreateDetail")",
                    type: 'POST',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    dataType: "json",
                    success: function (response) {
                        loadLessons();
                        $("#myModal").modal('hide');
                    }
                });
            });
        });

        function loadLessons() {
            var classId = $("#classes").val();
            var disciplineId = $("#disciplines").val();
            var weekStart = $("#weeks").val();

            if (classId && disciplineId && weekStart) {
                $.get('/Lesson/GetLessons?classId=' + classId + '&disciplineId=' + disciplineId + '&weekStart=' + weekStart, function (lessons) {
                    $("#journal").html(lessons);

                    $(".detail").click(function () {
                        var detail = $(this);
                        var studentId = detail.find(".studentId").val();
                        $("#modalStudentId").val(studentId);
                        var lessonId = detail.find(".lessonId").val();
                        $("#modalLessonId").val(lessonId);
                        var lessonDetailId = detail.find(".lessonDetailId").val();
                        $("#modalLessonDetailId").val(lessonDetailId);
                    });
                });
            }
        }
</script>
}

School.Web/Views/Lesson/_Lesson.cshtml
@using School.Web.Models.ViewModels
@model IEnumerable<School.Web.Models.ViewModels.LessonViewModel>
@if (Model.Any())
{

    <div class="module-option clearfix" style="border: none; padding-bottom: 0.5em;">
        <div class="pull-left">
            [Преподаватель: @ViewBag.TeacherName]
        </div>
        <div class="pull-right">
            Проведено занятий: @ViewBag.AddedLessons / @ViewBag.NumberOfLessons
        </div>
    </div>

    <div class="module-body table" style="padding-bottom: 0em;">
        <table class="table table-bordered table-hover-cells">
            <thead>
                <tr>
                    <th class="span3">Домашнее задание</th>
                    <th class="span1" style="border-left: none;"></th>

                    @foreach (var lesson in Model)
                    {
                        <th style="text-align: center;">@lesson.HomeWork</th>
                    }
                </tr>
            </thead>
        </table>
    </div>

    <div class="module-body table" style="padding-bottom: 3em;">
        <table class="table table-bordered table-hover-cells">
            <thead>
                <tr>
                    <th class="span1" style="text-align: center;">#</th>
                    <th class="span3">Ученик</th>

                    @foreach (var lesson in Model)
                    {
                        <th style="text-align: center;">@lesson.LessonDate.ToString("dd.MM.yyyy")</th>
                    }
                </tr>
            </thead>
            <tbody>
                @{
                    var index = 0;
                    foreach (var student in (List<StudentViewModel>)ViewBag.Students)
                    {
                        <tr class="@(index % 2 == 0 ? "even" : "odd") gradeX">
                            <td style="text-align: center;">@(++index)</td>
                            <td>
                                @(student.LastName + " " + student.FirstName ?? "" + " " + student.MiddleName ?? "")
                            </td>
                            @foreach (var lesson in Model)
                            {
                                var lessonDetail = lesson.LessonDetails.LastOrDefault(ld => ld.StudentId == student.StudentId);

                                <td href="#myModal" data-toggle="modal" style="text-align: center;" class="detail">
                                    <input type="hidden" class="lessonId" value="@lesson.LessonId" />
                                    <input type="hidden" class="studentId" value="@student.StudentId" />
                                    @if (lessonDetail != null)
                                    {
                                        <input type="hidden" class="lessonDetailId" value="@lessonDetail.LessonDetailId" />
                                        if (lessonDetail.Grade > 0)
                                        {
                                            <b class="label" style="background-color: @(lessonDetail.Grade == 5 ? "green" : "")@(lessonDetail.Grade == 4 ? "orange" : "")@(lessonDetail.Grade == 3 ? "orangered" : "")@(lessonDetail.Grade == 2 ? "red" : "");padding: 0.5em;">@lessonDetail.Grade</b>
                                            <b @((lessonDetail.Attention ?? false) ? "style=color:red;" : "")>@lessonDetail.Comment</b>
                                        }
                                    }
                                </td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="module-option clearfix">
        <div class="alert alert-info">
            <strong>На выранной неделе нет занятий.</strong>
        </div>
    </div>
}