School.Web/Models/Material.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models
{
    public class Material
    {
        public Material()
        {
            CreatedAt = DateTime.Now;
        }

        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string Authors { get; set; }
        public int Pages { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public virtual List<Discipline> Disciplines { get; set; }
    }
}

School.Web/Models/ViewModels/MaterialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace School.Web.Models.ViewModels
{
    public class MaterialViewModel
    {
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string Authors { get; set; }
        public int Pages { get; set; }
    }
}

School.Web/Controllers/DisciplineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Web.Models;
using AutoMapper;
using School.Web.Models.ViewModels;

namespace School.Web.Controllers
{
    public class DisciplineController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Discipline
        public async Task<ActionResult> Index()
        {
            var disciplines = await db.Disciplines.Where(x => x.IsDeleted == false).ToListAsync();
            var viewModels = Mapper.Map<List<DisciplineViewModel>>(disciplines);

            return View(viewModels);
        }

        // GET: Discipline/Create
        public async Task<ActionResult> Create()
        {
            var viewModel = new DisciplineViewModel();

            await CreateSelectLists();

            return View(viewModel);
        }

        // POST: Discipline/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DisciplineViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var discipline = Mapper.Map<Discipline>(viewModel);

                if (viewModel.SelectedMaterials != null && viewModel.SelectedMaterials.Count() > 0)
                {
                    var materials = await db.Materials.Where(m => viewModel.SelectedMaterials.Contains(m.MaterialId) && m.IsDeleted == false)
                        .ToListAsync();

                    discipline.Materials = materials;
                }
               
                db.Disciplines.Add(discipline);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Discipline/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var discipline = await db.Disciplines.FindAsync(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }

            var viewModel = Mapper.Map<DisciplineViewModel>(discipline);
            viewModel.SelectedMaterials = discipline.Materials.Select(m => m.MaterialId).ToList();

            await CreateSelectLists();

            return View(viewModel);
        }

        // POST: Discipline/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(DisciplineViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var discipline = await db.Disciplines.FindAsync(viewModel.DisciplineId);

                Mapper.Map(viewModel, discipline);

                if (viewModel.SelectedMaterials != null && viewModel.SelectedMaterials.Count() > 0)
                {
                    var materials = await db.Materials.Where(m => viewModel.SelectedMaterials.Contains(m.MaterialId) && m.IsDeleted == false)
                        .ToListAsync();

                    discipline.Materials.Clear();
                    discipline.Materials.AddRange(materials);
                }

                db.Entry(discipline).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Discipline/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var discipline = await db.Disciplines.FindAsync(id);
            if (discipline == null)
            {
                return HttpNotFound();
            }

            discipline.IsDeleted = true;

            db.Entry(discipline).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Discipline/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var discipline = await db.Disciplines.FindAsync(id);
            db.Disciplines.Remove(discipline);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private async Task CreateSelectLists()
        {
            var cls = await db.Classes.Where(x => x.IsDeleted == false)
                .Select(x => new { x.ClassId, ClassName = x.Number + x.Prefix })
                .ToListAsync();
            ViewBag.Classes = new SelectList(cls, "ClassId", "ClassName");

            var teachers = await db.Teachers.Where(x => x.IsDeleted == false)
                .Select(x => new {
                    x.TeacherId,
                    TeacherName = x.LastName + " " + (x.FirstName != null ? x.FirstName : "") + " "
                        + (x.MiddleName != null ? x.MiddleName : "")
                        + (", " + x.Speciality ?? "")
                })
                .ToListAsync();
            ViewBag.Teachers = new SelectList(teachers, "TeacherId", "TeacherName");

            ViewBag.Materials = await db.Materials.Where(x => x.IsDeleted == false)
               .Select(x => new MaterialViewModel
               {
                   MaterialId = x.MaterialId,
                   MaterialName = x.MaterialName + ", " + (x.Authors ?? "")
               })
               .ToListAsync();
        }
    }
}

School.Web/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School.Web.Models;
using AutoMapper;
using School.Web.Models.ViewModels;

namespace School.Web.Controllers
{
    public class MaterialController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Material
        public async Task<ActionResult> Index()
        {
            var materials = await db.Materials.Where(x => x.IsDeleted == false).ToListAsync();
            var viewModels = Mapper.Map<List<MaterialViewModel>>(materials);

            return View(viewModels);
        }

        // GET: Material/Create
        public ActionResult Create()
        {
            var viewModel = new MaterialViewModel();

            return View(viewModel);
        }

        // POST: Material/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MaterialViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var material = Mapper.Map<Material>(viewModel);

                db.Materials.Add(material);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Material/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var material = await db.Materials.FindAsync(id);
            if (material == null)
            {
                return HttpNotFound();
            }

            var viewModel = Mapper.Map<MaterialViewModel>(material);

            return View(viewModel);
        }

        // POST: Material/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(MaterialViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var material = await db.Materials.FindAsync(viewModel.MaterialId);

                Mapper.Map(viewModel, material);

                db.Entry(material).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Material/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var material = await db.Materials.FindAsync(id);
            if (material == null)
            {
                return HttpNotFound();
            }

            material.IsDeleted = true;

            db.Entry(material).State = EntityState.Modified;

            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Material/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var material = await db.Materials.FindAsync(id);
            db.Materials.Remove(material);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School.Web/Views/Material/Create.cshtml
@model School.Web.Models.ViewModels.MaterialViewModel
@{
    ViewBag.Title = "Добавить учебный матириал";
}

<div class="row">
    <div class="span3">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Material")">
                    <i class="menu-icon icon-circle-arrow-left"></i>Назад
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="module">
    <div class="module-head">
        <h3>Добавление учебного материала</h3>
    </div>
    <div class="module-body">
        <form class="form-horizontal row-fluid" action="@Url.Action("Create")" method="post">
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.MaterialId)
            <div class="control-group">
                <label class="control-label" for="basicinput">Наименование</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.MaterialName, new { @class = "span8", @placeholder = "Введите наименование..." })
                    @Html.ValidationMessageFor(m => m.MaterialName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Авторы</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Authors, new { @class = "span8", @placeholder = "Введите авторов..." })
                    @Html.ValidationMessageFor(m => m.Authors)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Количество страниц</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Pages, new { @class = "span8", @placeholder = "Введите количество страниц..." })
                    @Html.ValidationMessageFor(m => m.Pages)
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

School.Web/Views/Material/Edit.cshtml
@model School.Web.Models.ViewModels.MaterialViewModel
@{
    ViewBag.Title = "Редактировать учебный матириал";
}

<div class="row">
    <div class="span3">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Material")">
                    <i class="menu-icon icon-circle-arrow-left"></i>Назад
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="module">
    <div class="module-head">
        <h3>Редактирование учебного материала</h3>
    </div>
    <div class="module-body">
        <form class="form-horizontal row-fluid" action="@Url.Action("Edit")" method="post">
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.MaterialId)
            <div class="control-group">
                <label class="control-label" for="basicinput">Наименование</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.MaterialName, new { @class = "span8", @placeholder = "Введите наименование..." })
                    @Html.ValidationMessageFor(m => m.MaterialName)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Авторы</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Authors, new { @class = "span8", @placeholder = "Введите авторов..." })
                    @Html.ValidationMessageFor(m => m.Authors)
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="basicinput">Количество страниц</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Pages, new { @class = "span8", @placeholder = "Введите количество страниц..." })
                    @Html.ValidationMessageFor(m => m.Pages)
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

School.Web/Views/Material/Index.cshtml
@model IEnumerable<School.Web.Models.ViewModels.MaterialViewModel>
@{
    ViewBag.Title = "Учебные материалы";
}

<div class="span3">
    <div class="sidebar">
        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Home")">
                    <i class="menu-icon icon-circle-arrow-left"></i>К разделам
                </a>
            </li>
        </ul>

        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Index", "Discipline")">
                    <i class="menu-icon icon-list"></i>Дисциплины
                </a>
            </li>
            <li class="active">
                <a href="@Url.Action("Index", "Material")"><i class="menu-icon icon-book"></i>Учебные материалы</a>
            </li>
        </ul>
        <!--/.widget-nav-->

        <ul class="widget widget-menu unstyled">
            <li>
                <a href="@Url.Action("Create", "Material")">
                    <i class="menu-icon icon-plus"></i>Добавить материал
                </a>
            </li>
        </ul>
        <!--/.widget-nav-->
    </div>
    <!--/.sidebar-->
</div>
<!--/.span3-->
<div class="span9">
    <div class="content">
        <div class="module">
            <div class="module-head">
                <h3>
                    Учебные материалы
                </h3>
            </div>
            <div class="module-body table">
                <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display"
                       width="100%">
                    <thead>
                        <tr>
                            <th>
                                Наименование
                            </th>
                            <th>
                                Авторы
                            </th>
                            <th>
                                Страниц
                            </th>
                            <th>
                                Действия
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var index = 0;
                            foreach (var material in Model)
                            {
                                <tr class="@(index % 2 == 0 ? "even" : "odd") gradeX">
                                    <td>
                                        @material.MaterialName
                                    </td>
                                    <td>
                                        @material.Authors
                                    </td>
                                    <td>
                                        @material.Pages
                                    </td>
                                    <td class="center">
                                        <a href="@Url.Action("Edit", new { id = material.MaterialId })"><i class="icon-pencil" style="color: green;"></i></a>
                                        <a href="@Url.Action("Delete", new { id = material.MaterialId })"><i class="icon-trash" style="color: red;"></i></a>
                                    </td>
                                </tr>
                            }
                        }
                </tbody>
                @*<tfoot>
                        <tr>
                            <th>
                                Rendering engine
                            </th>
                            <th>
                                Browser
                            </th>
                            <th>
                                Platform(s)
                            </th>
                            <th>
                                Engine version
                            </th>
                            <th>
                                CSS grade
                            </th>
                        </tr>
                    </tfoot>*@
            </table>
        </div>
    </div>
</div>
<!--/.content-->
</div>
<!--/.span9-->